# Generated by Django 2.2.4 on 2024-04-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230219_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(verbose_name='发布时间')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('name', models.CharField(max_length=256, verbose_name='评论者昵称')),
                ('user_url', models.CharField(max_length=256, verbose_name='评论者主页')),
                ('img', models.CharField(max_length=256, verbose_name='评论者头像')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('reply', models.IntegerField(verbose_name='回复数')),
                ('sex', models.CharField(max_length=256, verbose_name='评论者性别')),
                ('loc', models.CharField(max_length=256, verbose_name='评论者所在地')),
                ('emotion', models.CharField(choices=[('消极', '消极'), ('积极', '积极'), ('中性', '中性')], default='', max_length=256, verbose_name='情感')),
            ],
            options={
                'verbose_name_plural': '评论管理',
            },
        ),
    ]
