# Generated by Django 4.2.27 on 2026-03-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='high_risk', max_length=32, verbose_name='预警类型')),
                ('risk_level', models.IntegerField(default=0, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理'), ('closed', '已关闭')], default='pending', max_length=16, verbose_name='处理状态')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='预警原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
            },
        ),
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='标签编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签描述')),
                ('risk_level', models.IntegerField(default=0, verbose_name='风险等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签定义',
                'verbose_name_plural': '标签定义',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('svm', 'TF-IDF + SVM'), ('lr', 'TF-IDF + LogisticRegression'), ('textcnn', 'TextCNN'), ('rule', '规则词典'), ('fusion', '融合模型')], max_length=16, verbose_name='模型类型')),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='模型文件路径')),
                ('vectorizer_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='向量器路径')),
                ('metrics_json', models.TextField(blank=True, null=True, verbose_name='评估指标JSON')),
                ('status', models.CharField(choices=[('training', '训练中'), ('ready', '可用'), ('disabled', '已停用'), ('failed', '训练失败')], default='ready', max_length=16, verbose_name='状态')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型信息',
                'verbose_name_plural': '模型信息',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TextSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='来源名称')),
                ('source_type', models.CharField(choices=[('tieba', '贴吧'), ('csv', 'CSV导入'), ('excel', 'Excel导入'), ('json', 'JSON导入'), ('manual', '手工录入'), ('api', '外部接口')], default='tieba', max_length=16, verbose_name='来源类型')),
                ('source_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='来源标识')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文本来源',
                'verbose_name_plural': '文本来源',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='emotion',
            field=models.CharField(choices=[('没有抑郁倾向', '没有抑郁倾向'), ('一般抑郁倾向', '一般抑郁倾向'), ('轻度抑郁倾向', '轻度抑郁倾向'), ('严重抑郁倾向', '严重抑郁倾向')], default='', max_length=256, verbose_name='情感'),
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='任务状态')),
                ('params_json', models.TextField(blank=True, null=True, verbose_name='训练参数JSON')),
                ('result_json', models.TextField(blank=True, null=True, verbose_name='训练结果JSON')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='创建人')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelinfo', verbose_name='目标模型')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=64, verbose_name='模块')),
                ('action', models.CharField(max_length=128, verbose_name='动作')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误')], default='info', max_length=16, verbose_name='日志级别')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=64, null=True, verbose_name='处理动作')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.alertrecord', verbose_name='预警')),
                ('final_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.labeldefinition', verbose_name='最终标签')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='复核人')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
            },
        ),
        migrations.CreateModel(
            name='RawText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='外部ID')),
                ('author_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='作者')),
                ('content', models.TextField(verbose_name='原始文本')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('new', '新建'), ('cleaned', '已清洗'), ('labeled', '已标注'), ('predicted', '已分析'), ('reviewed', '已复核'), ('archived', '已归档')], default='new', max_length=16, verbose_name='处理状态')),
                ('dedup_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='去重哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.textsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '原始文本',
                'verbose_name_plural': '原始文本',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0, verbose_name='预测概率')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='风险得分')),
                ('risk_level', models.IntegerField(default=0, verbose_name='风险等级')),
                ('hit_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='命中关键词')),
                ('detail_json', models.TextField(blank=True, null=True, verbose_name='详情JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelinfo', verbose_name='模型')),
                ('predicted_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.labeldefinition', verbose_name='预测标签')),
                ('raw_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='app.rawtext', verbose_name='原始文本')),
            ],
            options={
                'verbose_name': '预测结果',
                'verbose_name_plural': '预测结果',
            },
        ),
        migrations.CreateModel(
            name='CleanText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_content', models.TextField(verbose_name='清洗后文本')),
                ('tokenized_content', models.TextField(blank=True, null=True, verbose_name='分词结果')),
                ('removed_special_chars', models.BooleanField(default=True, verbose_name='是否清洗特殊字符')),
                ('removed_stopwords', models.BooleanField(default=False, verbose_name='是否去停用词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('raw_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_result', to='app.rawtext', verbose_name='原始文本')),
            ],
            options={
                'verbose_name': '清洗文本',
                'verbose_name_plural': '清洗文本',
            },
        ),
        migrations.CreateModel(
            name='AnnotationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_split', models.CharField(default='train', max_length=16, verbose_name='数据集划分')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='标注时间')),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='标注人')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.labeldefinition', verbose_name='标签')),
                ('raw_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='app.rawtext', verbose_name='原始文本')),
            ],
            options={
                'verbose_name': '标注记录',
                'verbose_name_plural': '标注记录',
            },
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='app.predictionresult', verbose_name='关联预测'),
        ),
    ]
