# Generated by Django 4.2.27 on 2026-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alertrecord_labeldefinition_modelinfo_textsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtext',
            name='status',
            field=models.CharField(choices=[('pending_clean', '未清洗'), ('cleaned', '已清洗'), ('pending_label', '待标注'), ('labeled', '已标注'), ('pending_predict', '待预测'), ('predicted', '已预测'), ('alerted', '已预警'), ('reviewed', '已复核')], default='pending_clean', max_length=16, verbose_name='处理状态'),
        ),
    ]
