# Generated by Django 4.2.27 on 2026-03-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_rawtext_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecord',
            name='alert_level',
            field=models.IntegerField(default=0, verbose_name='预警等级'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='prediction_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_records', to='app.predictionresult', verbose_name='预测结果'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='raw_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='app.rawtext', verbose_name='原始文本'),
        ),
        migrations.AddField(
            model_name='alertrecord',
            name='trigger_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='触发原因'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='final_risk_score',
            field=models.FloatField(default=0.0, verbose_name='最终风险分'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='is_alert_triggered',
            field=models.BooleanField(default=False, verbose_name='是否触发预警'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='model_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_records', to='app.modelinfo', verbose_name='模型信息'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='probability_score',
            field=models.FloatField(default=0.0, verbose_name='模型概率分'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='rule_score',
            field=models.FloatField(default=0.0, verbose_name='规则分'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='alert_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='app.alertrecord', verbose_name='预警记录'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='review_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='复核备注'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='review_result',
            field=models.CharField(blank=True, choices=[('false_positive', '误报'), ('confirmed_high_risk', '确认高风险'), ('downgraded', '降级处理'), ('upgraded', '升级处理'), ('processed', '已处理')], max_length=32, null=True, verbose_name='复核结果'),
        ),
    ]
