# Generated by Django 4.2.27 on 2026-03-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alertrecord_alert_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='配置键')),
                ('value', models.CharField(max_length=255, verbose_name='配置值')),
                ('value_type', models.CharField(default='str', max_length=16, verbose_name='值类型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='配置说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='config_json',
            field=models.TextField(blank=True, null=True, verbose_name='模型配置JSON'),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模型说明'),
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=32, verbose_name='模型版本')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='准确率')),
                ('precision', models.FloatField(default=0.0, verbose_name='精确率')),
                ('recall', models.FloatField(default=0.0, verbose_name='召回率')),
                ('f1_score', models.FloatField(default=0.0, verbose_name='F1')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('is_active_snapshot', models.BooleanField(default=False, verbose_name='当时是否启用')),
                ('model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.modelinfo', verbose_name='模型')),
            ],
            options={
                'verbose_name': '模型评估记录',
                'verbose_name_plural': '模型评估记录',
            },
        ),
    ]
