# Generated by Django 4.2.27 on 2026-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_systemconfig_modelinfo_config_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSelfCheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=16, verbose_name='检测模式')),
                ('summary', models.CharField(max_length=32, verbose_name='结果摘要')),
                ('has_error', models.BooleanField(default=False, verbose_name='是否存在错误')),
                ('detail_json', models.TextField(verbose_name='详细结果JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型自检记录',
                'verbose_name_plural': '模型自检记录',
            },
        ),
    ]
