# Generated by Django 4.2.27 on 2026-03-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_modelselfcheckrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('prediction_result', '预测结果'), ('alert_record', '预警记录'), ('self_check_history', '自检历史')], max_length=32, verbose_name='导出类型')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=16, verbose_name='导出格式')),
                ('filter_json', models.TextField(blank=True, null=True, verbose_name='筛选条件JSON')),
                ('export_count', models.IntegerField(default=0, verbose_name='导出条数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导出时间')),
                ('exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='导出人')),
            ],
            options={
                'verbose_name': '导出日志',
                'verbose_name_plural': '导出日志',
            },
        ),
    ]
