# Generated by Django 4.2.27 on 2026-03-27 15:39

from django.db import migrations, models


def set_user_role(apps, schema_editor):
    User = apps.get_model('app', 'User')
    # 兼容现有账号: admin账号赋管理员，其余默认普通用户
    User.objects.filter(username='admin').update(role='admin')
    User.objects.exclude(username='admin').update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_exportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('analyst', '分析员'), ('reviewer', '审核员')], default='user', max_length=16, verbose_name='角色'),
        ),
        migrations.RunPython(set_user_role, migrations.RunPython.noop),
    ]
