# Generated by Django — data migration preserves prior behavior (all ready rows visible)

from django.db import migrations, models


def forwards_listed(apps, schema_editor):
    ModelInfo = apps.get_model('app', 'ModelInfo')
    ModelInfo.objects.filter(status='ready').update(listed_for_users=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_model_subdir_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='listed_for_users',
            field=models.BooleanField(
                default=False,
                help_text='勾选后：该登记会出现在前台「在线预测」模型列表，且用户管理中可按该类型分配权限；未勾选则仅后台可见。',
                verbose_name='前台与用户权限可见',
            ),
        ),
        migrations.RunPython(forwards_listed, migrations.RunPython.noop),
    ]
