# Generated by Django 4.2.27 on 2026-03-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_modelinfo_hf_transformers_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRawTextMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rawtext_map', to='app.comment', verbose_name='评论')),
                ('raw_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_maps', to='app.rawtext', verbose_name='原始文本')),
            ],
            options={
                'verbose_name': '评论原始文本映射',
                'verbose_name_plural': '评论原始文本映射',
            },
        ),
    ]
