# Generated by Django 4.2.27 on 2026-03-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_commentrawtextmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_model_types',
            field=models.TextField(blank=True, default='', help_text='JSON 数组，如 ["svm","textcnn"]；留空表示不限制（前台仅能看到「就绪且前台可见」的模型登记）', verbose_name='可用算法类型'),
        ),
    ]
