# Generated by Django 4.2.27 on 2026-03-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_commentrawtextmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_length', models.IntegerField(default=0, verbose_name='输入文本长度')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='结果消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                (
                    'model_info',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='usage_logs',
                        to='app.modelinfo',
                        verbose_name='调用模型',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='app.user',
                        verbose_name='调用用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '预测调用日志',
                'verbose_name_plural': '预测调用日志',
            },
        ),
    ]
