# Generated by Django 4.2.27 on 2026-03-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_predictionusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='方案名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('total_quota', models.IntegerField(default=0, verbose_name='总调用额度')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('allowed_model_types_json', models.TextField(blank=True, default='', help_text='JSON 数组，如 ["svm","textcnn"]；为空表示按具体模型限制或不限制。', verbose_name='允许的模型类型')),
                ('allowed_model_ids_json', models.TextField(blank=True, default='', help_text='JSON 数组，如 [1,2,3]；为空表示按类型限制或不限制。', verbose_name='允许的模型ID')),
            ],
            options={
                'verbose_name': '模型授权方案',
                'verbose_name_plural': '模型授权方案',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_quota', models.IntegerField(default=0, verbose_name='剩余额度')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待生效'), ('active', '生效中'), ('expired', '已过期'), ('suspended', '已停用')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_plans',
                        to='app.modelplan',
                        verbose_name='方案',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plans',
                        to='app.user',
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '用户套餐',
                'verbose_name_plural': '用户套餐',
            },
        ),
        migrations.CreateModel(
            name='QuotaUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(default=0, verbose_name='扣减数量')),
                ('before_quota', models.IntegerField(default=0, verbose_name='扣减前额度')),
                ('after_quota', models.IntegerField(default=0, verbose_name='扣减后额度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'model_info',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='app.modelinfo',
                        verbose_name='模型',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='app.userplan',
                        verbose_name='用户套餐',
                    ),
                ),
                (
                    'usage_log',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quota_logs',
                        to='app.predictionusagelog',
                        verbose_name='调用日志',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='app.user',
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '额度扣减流水',
                'verbose_name_plural': '额度扣减流水',
            },
        ),
    ]
