# Generated by Django 4.2.27 on 2026-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_modelplan_userplan_quotausagelog'),
        ('app', '0020_alter_user_allowed_model_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmExperimentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='实验名称')),
                ('dataset_version', models.CharField(max_length=64, verbose_name='数据集/数据版本')),
                ('algorithm_type', models.CharField(choices=[('svm', 'SVM'), ('knn', 'KNN'), ('rf', '随机森林'), ('dt', '决策树'), ('lr', '逻辑回归'), ('textcnn', 'TextCNN'), ('textrcnn', 'TextRCNN')], max_length=16, verbose_name='算法类型')),
                ('hyperparams_json', models.TextField(blank=True, default='{}', verbose_name='超参数JSON')),
                ('training_time_sec', models.FloatField(blank=True, null=True, verbose_name='训练时间(秒)')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='Accuracy')),
                ('precision', models.FloatField(default=0.0, verbose_name='Precision')),
                ('recall', models.FloatField(default=0.0, verbose_name='Recall')),
                ('f1_score', models.FloatField(default=0.0, verbose_name='F1')),
                ('auc', models.FloatField(blank=True, null=True, verbose_name='AUC')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '算法对比实验记录',
                'verbose_name_plural': '算法对比实验记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
