"""
Django settings for DjangoWeb project.

Generated by 'django-admin startproject' using Django 2.2.13.
# 项目原作者：赵有才 
# 联系方式：creepreme@126.com/ wechat: zyb1209121xty
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from DjangoWeb import config

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&a&k6+=i6u3akby#-)4&*jqz%xz%@y83a7cantf5e+wk6k7f-b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.DemoConfig',

]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
SIMPLEUI_HOME_INFO = False # 不显示信息
SIMPLEUI_HOME_QUICK = False # 快捷导航
SIMPLEUI_HOME_ACTION = False # 最近行为
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com' # 首页
SIMPLEUI_HOME_ICON = 'fa fa-user' # 首页标题
# SIMPLEUI_INDEX = 'https://www.88cto.com' # 设置点击首页图标跳转的地址
# SIMPLEUI_CONFIG = {
#     #保留系统菜单
#     'system_keep': True,
#     # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
#     # 'menu_display': ['Simpleui', '测试', '权限认证', '动态菜单测试'],
#     'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
#     'menus': [
#         {
#             # 一级菜单
#             'name': '可视化',
#             'icon': 'fa-fw fa fa-leaf',
#             'models': [{
#                 'name': '文章报表',
#                 'icon': 'far fa-surprise',
#                 'url': 'https://www.baidu.com',
#                 # 浏览器新标签中打开
#                 'newTab':False
#             }]
#         },
#     ]
# }



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR ,'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = config.DATABASES

# 默认内存缓存（融合策略离线对比等指标缓存；未配置时 Django 为 DummyCache 会导致每次全量重算）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'django-web-locmem',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS =  (
    os.path.join(BASE_DIR,'static'),
)

# 图片储存根路径
MEDIA_ROOT = BASE_DIR + '/media'
# 图片访问url
MEDIA_URL = '/media/'